### PR TITLE
Changed port number to 3000 and added login

### PR DESCRIPTION
**Pull request by Gutierrezjdr**
Changed port to 3000 in server.js according to instructions and added login and password into index.html.

### CODE REVIEW

**Comment by Gutierrezjdr** [comment]
Hey @yizongk  can you review this before I merge.

**Comment by zhik** [comment]
Don't change the port to 3000 in server.js, it will conflict with react.

**Comment by Gutierrezjdr** [comment]
so take off password text input @zhik ?

**Comment by Gutierrezjdr** [comment]
Okay so then I will change the README then.

**Comment by yizongk** [comment]
Ya, React is using port 3000, i changed it to port 5000 for that reason. As of right now, React read from port 3000 and redirect it to port 5000 when it interacts with server.js

**Comment by yizongk** [comment]
Is there also a way to do the form in React? by editing  src/myapp/client/src/App.js? Because I am not sure if editing the index.html is a good idea. That html is meant to be a blank page that will be updated with content returned from App.js

Which means that App.js in the future can potentital wipe out the form input boxes in the future as it will do its job by updating that html with new content by overwriting certain area of the html.

**Pull request closed without merging**
